service: booking-api

provider:
  name: aws
  runtime: nodejs20.x
  region: eu-north-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:PutItem
            - dynamodb:DeleteItem
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:UpdateItem
          Resource: 
            - arn:aws:dynamodb:eu-north-1:*:table/BookingTable

functions:
  listRooms:
    handler: handler.listRooms
    events:
      - http:
          path: rooms
          method: get

  listAllBookings:
    handler: handler.listAllBookings
    events:
      - http:
          path: bookings
          method: get

  createBooking:
    handler: handler.createBooking
    events:
      - http:
          path: bookings
          method: post

  cancelBooking:
    handler: handler.cancelBooking
    events:
      - http:
          path: bookings/{id}
          method: delete
      
  updateBooking:
    handler: handler.updateBooking
    events:
      - http:
          path: bookings/{id}
          method: put

resources:
  Resources:
    BookingTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: BookingTable  # Matchar namnet med tabellen i Lambda-koden
        AttributeDefinitions:
          - AttributeName: bookingId
            AttributeType: S
        KeySchema:
          - AttributeName: bookingId
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST